version: '3.3'

services:
   sogd_db:
     image: mysql:5
     volumes:
       - sogd_db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: someROOTpassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   sogd_webserver:
     image: wordpress:5
     volumes:
      - ./plugin:/var/www/html/wp-content/plugins/sogd
      - ./theme:/var/www/html/wp-content/themes/sogd
     depends_on:
       - sogd_db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: sogd_db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    sogd_db: {}
